---
version: '3.8'

services:
  pgsql:
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: votebox
      POSTGRES_PASSWORD: votebox
      PGDATA: /data
    volumes:
      - 'pgdata:/data'

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '8080:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@votebox.io
      PGADMIN_DEFAULT_PASSWORD: admin

volumes:
  pgdata: {}

